### ISSUE TITLE
Checking if partial fees are acctual fees that user will pay

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#125]

**Comment by kaliman93** [comment]
In the image below there is console.log-ed paymentInfo and transaction hash of [this](https://assethub-rococo.subscan.io/extrinsic/0xe9f2576349f614d64644abda6014184c7d93fc1b2356ee689bfc3a4d50d4f6b5) swap
![Image](https://github.com/MVPWorkshop/dot-acp-ui/assets/42982386/cd829d5c-452c-4992-b2a7-946f2da6f775)

From the information from the image above and bc scanner link, i can infer that the partialFee parameter returned in peymentInfo function call is the actual amount of fees user pay's for the transaction
