### ISSUE TITLE
Investigate Pool reserve error

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#156]
See why this error is happening. Prevent it from happening - inform user that this will happen.

![Image](https://github.com/MVPWorkshop/dot-acp-ui/assets/101146655/2a2cffd9-7a60-4cf8-85f0-98f531694b3c)

Relates to the story #41

**Comment by ngrujicic** [comment]
amount_out - amount we want to receive
reserve_out - current pool reserves for the token we want to get is below the number we want to receive

solution: show warning message when the amount_out >= reserve_out

**Comment by gagi13** [comment]
Reprioritized for now since we couldn't figure out

**Comment by gagi13** [comment]
**Update**: Groom this error with Kaliman

**Comment by ngrujicic** [comment]
could not reproduce the error, the error should happen when you are not having enough funds in your pool, when you are trying to get more tokens out of the pool than that is possible, we are already checking if we have enough tokens in the pool before we can do the swap, so i am not sure how this happened.

@gagi13 @ra79sta  maybe we should keep this open until we manage to reproduce it and then try to handle the error ?
