### ISSUE TITLE
Show transaction detail info in wallet

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#160]
Transaction detail information in the wallet are not showed.

![Image](https://github.com/MVPWorkshop/dot-acp-ui/assets/101146655/ce5186e7-9452-41aa-8784-7a574a1a6645)

**Comment by ngrujicic** [comment]
i just tested this multiple times for every transaction we have, it was working fine, showing the transaction details every time

**Comment by gagi13** [comment]
It does not work for my wallet, we need to figure out why.
