### ISSUE TITLE
Load button for reading tokens from the wallet

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#161]
Currently, while our wallet is fetching token balances, we show to user that the wallet is connecting. Since that takes a while, a better option would be to separate connect wallet from fetching balances. So connect the wallet at once and to create this token loader when trying to choose tokens for swap or pool pair after the wallet is connected. Below is the suggested design.

Relates to #213

**Comment by jakyriec** [comment]
![Screenshot 2023-09-26 at 11 25 06](https://github.com/MVPWorkshop/dot-acp-ui/assets/142032160/052cf270-1737-43ae-9a66-9218ec24ccdf)

This is the look we want to achieve while tokens are still loading, ghost loader with some nice animation.

**Comment by Kouteki** [comment]
Current state
**Connect wallet** loader is spinning until wallets are connected and assets fetched

Desired state

1. **Connect wallet** loader is spinning until wallets are connected.
2. **Token selectors** loaders are spinning once wallets are connected, and until assets are fetched
