### ISSUE TITLE
Explore swap not triggered

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#163]
Sometimes swap function does not want to be triggered on a click of a button (NSS-RASTA / RASTA-WND)

Relates to the story #41

**Comment by ngrujicic** [comment]
i tested swap for every pair we have and it was triggered every time, we will test the swap with unit test once we have time for it just to be sure.

**Comment by gagi13** [comment]
Okay, we will see in the final testing if this will occur again.
