### ISSUE TITLE
Polkadot Oracles Spike (test with DOT)

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#172]
Find the best way to calculate token prices
- [x] Try to find all coins somewhere listed for Polkadot ecosystem
- [x] Calculate and show token price for WND in DOT
- [x] Calculate other token prices from WND in our DEX

**Comment by kaliman93** [comment]
Considering that most of [Assets](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-asset-hub-rpc.polkadot.io#/assets) in Polkadot Asset Hub aren’t listed anywhere (on any exchange), price feeds would be impossible to get.

So i think we have to go with alternative, where we will quote price of 1 Asset in Native Token (DOT, KSM, WND...) and use that value `CalculatedPriceOfAssetInNativeToken` to determine $ value of the asset. We can do it by multiplying `CalculatedPriceOfAssetInNativeToken` with dollar price of native token, which we can get from any oracle/price aggregator (coingecko for example).

For our purposes on testnet (Westend and Rococo) we can assume that prices in $ of native tokens, on those test network, is the same as for the DOT, and we can fetch it from `/simple/token-price/{id}` endpoint on [coingecko api](https://www.coingecko.com/en/api/documentation) (for example)
