### ISSUE TITLE
Numbers turn to zero

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#202]
After typing for a long in a swap (add liquidity) amount box, at some point numbers start presenting as zeros even if a user is typing regular numbers. 
Video [here](https://www.loom.com/share/d7fa3c072d5b42949858229a1fb65d1c?sid=51b9eaf2-03ce-4cdc-817d-273cf1e9f78a)

**Comment by ngrujicic** [comment]
@ra79sta this issue is solved, it was solved automatically when i added the restriction to input max 15 numbers, if you go over 16 it will break and start the with the 0 issue
