### ISSUE TITLE
[BUG] Research error "token below minimum"

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#214]
**Describe the bug**
When the user wants to swap coins, sometimes the swap can not be completed because of this error. 

**To Reproduce**
1. Go to swap
2. Choose NG1312 and ETH to swap
3. Choose some amount and wait for this error. 

**Expected behavior**
- We should figure out what this error means so we can inform the user what behavior he should change and what triggered this error. 

**Your environment (please complete the following information):**

- macOS Monetrey, version 12.6.7
- Google Chrome

**Comment by ngrujicic** [comment]
Deposit couldn't happen due to the amount being too low. This is usually because the
account doesn't yet exist and the deposit wouldn't bring it to at least the minimum needed for existance.

BelowMinimum

**Comment by ngrujicic** [comment]
Here you can see that when i search in the balances section of the polakdot.js app for the ETH token with the id 10,111 that the account dosen't exist: "No accounts with balances found for the asset"

![Image](https://github.com/MVPWorkshop/dot-acp-ui/assets/126670759/10eb98a7-7c2a-48a1-9b9c-aabf9c778165)

**Comment by ngrujicic** [comment]
BelowMinimum: to handle this error we need to check if the user has the token he wants to receive already in his account, if he does not then we need to check if the amount of the token we will receive is equal or bigger then the minimal amount for this token

Token can not create: we need to show to a user a message telling him that he has too many assets on his account

15 maximum assets + native token
