### ISSUE TITLE
[BUG] Research error "Token can not create"

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#215]
**Since this error is on Asset Hub end and not our end, just keep an eye on when it will be resolved.** 

**Describe the bug**
When user wants to swap tokens, sometimes this error occurs. 

**To Reproduce**
1. Go to swap
2. Choose NSS and MRT to swap
3. Choose some amount and wait for this error.

**Expected behavior**
We should figure out what this error means so we can inform the user what behavior he should change and what triggered this error.

**Screenshots**

**Your environment (please complete the following information):**
 - macOS Monetrey, version 12.6.7
 - Google Chrome

**Comment by Kouteki** [comment]
@ra79sta let's confirm that lowering the total number assets by burning resolves this bug.

**Comment by Kouteki** [comment]
Acceptance criteria:
- Add warning: 
`Your account has reached the limit of 16 assets and liquidity pools total. Burn or send all of assets of a certain type from your account, or withdraw all assets from a pool to make room for another type. Alternatively connect another wallet and use it for new assets and pools.`
- Determine whether Rococo has the same bug

**Comment by Kouteki** [comment]
Reminder (from the duplicate bug report)

```
You can not receive new tokens if you have 16 assets/tokens already on your account.

We need to show to the user a warning message telling him that he has too many assets on his account.

Important note: we need to check if this is something that is happening only on the test networks.
```
