### ISSUE TITLE
[BUG] Explore Provided maximum amount is not sufficient for swap

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#285]
**Describe the bug**
This is the error message the user can get when doing a swap - "Provided maximum amount is not sufficient for swap". Investigate if this happens due to slippage. If so, show this message instead: "The transaction could not be completed due to the set slippage."

**To Reproduce**
Not sure how to reproduce it since it is not clear when and how it happens. 

**Expected behavior**
While swapping, the transaction broke, and the user got this message - Provided maximum amount is not sufficient for swap.

**Screenshots**

**Your environment (please complete the following information):**
 - Happened on both networks and with all wallets. After refreshing and setting the higher slippage, transaction often occurs successfully.

**Comment by ngrujicic** [comment]
i can not reproduce this error
