### ISSUE TITLE
[BUG] Adding multiple accounts

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#297]
**Describe the bug**
Once the user connects wallet for the first time, he chooses what accounts from that wallet he is willing to add to the app. After that, each time it is by default that few accounts. In case user ads accounts to his wallet, those won't be visible.

**Comment by gagi13** [comment]
Sync with Staca fore more info

**Comment by zarej** [comment]
Tested on all supported wallets:
- PolkadotJS - new account is present just after connection to wallet
- Subwallet - the same
- Encrypt - the same
- Talisman - must be added in wallet UI at COnnected Sites to be added new account
