### ISSUE TITLE
Explore dotACP deployment on Kusama

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#308]
Set parameters for Kusama and explore what time and effort we will need for deploying dotACP on Kusama. Make assumption on how much this testing will cost.

**Comment by ngrujicic** [comment]
Changes needed:

1. RPC URL (change in environment).
2. Token Name (change on few places or via configuration file).
3. Change endpoint path to parent(MultiAsssetId).
4. Buy KSM(we would need aprox. 4 KSM per pool - 26$ per KSM, for 3 pools 312$).
4. Create 3 new tokens(gas fee per transaction aprox. 0.0028728232 dollars).
5. Create 3 new pools and test.

we would need aprox. 315$ for testing - we can get the money out minus the transaction fees.

Rough TE: 2 days
