### ISSUE TITLE
[BUG] Westend: App does not work

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#330]
**Describe the bug**
When I connect wallet to Westend dotACP, I can not swap. It won't read my tokens. Pools can't be seen. Only Add position can access, but the token ratio is not working. 

**To Reproduce**
1. Go to https://dot-acp-westmint.mvpworkshop.co/swap 
2. Click on connect wallet.
3. Try to swap, view pools or whatever else. 

**Screenshots**
![Image](https://github.com/MVPWorkshop/dot-acp-ui/assets/101146655/113b27ee-467f-4fbb-a55c-db7bd34301a8)

**Your environment (please complete the following information):**
 - Mac
 - Chorome
 - Westend chain

**Comment by zarej** [comment]
Resolved https://github.com/MVPWorkshop/dot-acp-ui/pull/334
