### ISSUE TITLE
[BUG] : user balance keeps loading after connecting wallet

### ISSUE THREAD

**Issue by muddlebee** [MVPWorkshop/dot-acp-ui#365]
1. Go to https://app.dotacp.mvpworkshop.co/swap and connect wallet
2. Balance is not loading

![image](https://github.com/MVPWorkshop/dot-acp-ui/assets/8139783/0b7869f6-68b0-4bbb-95d7-5199eefe731b)

**Comment by muddlebee** [comment]
it takes a few minutes to load the balance. too slow I guess.

**Comment by gagi13** [comment]
Hi @muddlebee and thank you for opening this issue.
The asset conversion pallet function for fetching balances works by reading metadata for each asset that exists on Asset Hub, and that is why it takes long. However, we we managed to optimize time to be around 5 seconds now - will merge it EOD.
We will also try to find a different way of fetching balances so hopefully will improve this even more soon. I will let you know once this is resolved.
Cheers!
