### ISSUE TITLE
Change error message when no wallet installed

### ISSUE THREAD

**Issue by fjovakaric** [MVPWorkshop/dot-acp-ui#71]
![Image](https://user-images.githubusercontent.com/10724488/264378693-9539aafa-73a1-4582-bf1a-f3dc23dd3e2b.png)

Change copy to:
"No wallet found!"

**Comment by gagi13** [comment]
I still got the same message. We need to resolve


![Image](https://github.com/MVPWorkshop/dot-acp-ui/assets/101146655/1eb84ef5-71e2-417b-bb0e-cd6953a07cc2)

**Comment by gagi13** [comment]
Also, since now we have this pop-up this error won't happen so we need to show the message in the pop-up. Below  Connect to a wallet it should say: "No wallet found!" . 

@ra79sta 

![Image](https://github.com/MVPWorkshop/dot-acp-ui/assets/101146655/1f09d56e-9080-4658-804c-f3146d7aa2b1)
