### ISSUE TITLE
Connect swap to pallet

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#82]
Part of Story #41

**Comment by ngrujicic** [comment]
things to do:
1. calculate the amount of the other token in the swap(either receive or pay field can be edited, if we edit receive the other needs to update/change and vice versa, exact input - exact output functions).
2. calculate the slippage of the other token.
3. when user clicks on swap we need to call the swap function, sign and submit it with the wallet.
